/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    docs: Doc;
    tools: Tool;
    'navigation-links': NavigationLink;
    'sidebar-groups': SidebarGroup;
    'sidebar-items': SidebarItem;
    components: Component;
    'open-api-specs': OpenApiSpec;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    docs: DocsSelect<false> | DocsSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    'navigation-links': NavigationLinksSelect<false> | NavigationLinksSelect<true>;
    'sidebar-groups': SidebarGroupsSelect<false> | SidebarGroupsSelect<true>;
    'sidebar-items': SidebarItemsSelect<false> | SidebarItemsSelect<true>;
    components: ComponentsSelect<false> | ComponentsSelect<true>;
    'open-api-specs': OpenApiSpecsSelect<false> | OpenApiSpecsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'es' | 'fr' | 'de' | 'fa';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('admin' | 'user')[] | null;
  name?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs".
 */
export interface Doc {
  id: number;
  title: string;
  /**
   * URL slug for the documentation page
   */
  slug: string;
  /**
   * Brief description for SEO and previews
   */
  description?: string | null;
  /**
   * Markdown content for the documentation page
   */
  content: string;
  /**
   * Order for sorting pages
   */
  order?: number | null;
  /**
   * Parent documentation page for nested structure
   */
  parent?: (number | null) | Doc;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  name: string;
  description?: string | null;
  type: 'utility' | 'admin' | 'content' | 'analytics';
  enabled?: boolean | null;
  /**
   * Tool-specific configuration options
   */
  configuration?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  permissions?: ('admin' | 'editor' | 'author' | 'public')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-links".
 */
export interface NavigationLink {
  id: number;
  label: string;
  url: string;
  /**
   * Open link in new tab
   */
  external?: boolean | null;
  enabled?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidebar-groups".
 */
export interface SidebarGroup {
  id: number;
  title: string;
  /**
   * Optional description for the group
   */
  description?: string | null;
  /**
   * Icon name (e.g., "home", "settings")
   */
  icon?: string | null;
  enabled?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  /**
   * Whether this group should be expanded by default
   */
  defaultOpen?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidebar-items".
 */
export interface SidebarItem {
  id: number;
  label: string;
  url: string;
  /**
   * Optional description for the item
   */
  description?: string | null;
  /**
   * Icon name (e.g., "file", "folder")
   */
  icon?: string | null;
  /**
   * Parent group (leave empty for root level items)
   */
  group?: (number | null) | SidebarGroup;
  /**
   * Parent item for nested structure
   */
  parent?: (number | null) | SidebarItem;
  /**
   * Open link in new tab
   */
  external?: boolean | null;
  enabled?: boolean | null;
  /**
   * Display order within group (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components".
 */
export interface Component {
  id: number;
  name: string;
  type:
    | 'accordion'
    | 'auto-type-table'
    | 'banner'
    | 'code-block'
    | 'files'
    | 'github-info'
    | 'graph-view'
    | 'zoomable-image'
    | 'inline-toc'
    | 'steps'
    | 'tabs'
    | 'type-table'
    | 'callout'
    | 'custom';
  /**
   * Description of what this component does
   */
  description?: string | null;
  /**
   * Text to insert in rich text editor (e.g., {{accordion}})
   */
  placeholder: string;
  /**
   * Component-specific configuration options
   */
  configuration?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Example usage or preview
   */
  preview?: string | null;
  enabled?: boolean | null;
  category?: ('layout' | 'content' | 'interactive' | 'data-display' | 'media') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-api-specs".
 */
export interface OpenApiSpec {
  id: number;
  title: string;
  /**
   * Description of this API specification
   */
  description?: string | null;
  /**
   * API version (e.g., v1, v2, 1.0.0)
   */
  version: string;
  /**
   * Upload your OpenAPI/Swagger JSON or YAML file
   */
  specFile: number | Media;
  /**
   * Base URL for the API (optional, can be overridden in spec)
   */
  baseUrl?: string | null;
  /**
   * URL slug for this API documentation (e.g., api/v1)
   */
  slug: string;
  /**
   * API servers/endpoints
   */
  servers?:
    | {
        url: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Authentication configuration
   */
  authentication?: {
    type?: ('none' | 'bearer' | 'apiKey' | 'basic' | 'oauth2') | null;
    /**
     * Name of the API key header/parameter
     */
    apiKeyName?: string | null;
    apiKeyLocation?: ('header' | 'query' | 'cookie') | null;
  };
  enabled?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'docs';
        value: number | Doc;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'navigation-links';
        value: number | NavigationLink;
      } | null)
    | ({
        relationTo: 'sidebar-groups';
        value: number | SidebarGroup;
      } | null)
    | ({
        relationTo: 'sidebar-items';
        value: number | SidebarItem;
      } | null)
    | ({
        relationTo: 'components';
        value: number | Component;
      } | null)
    | ({
        relationTo: 'open-api-specs';
        value: number | OpenApiSpec;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  name?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "docs_select".
 */
export interface DocsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  order?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  enabled?: T;
  configuration?: T;
  permissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation-links_select".
 */
export interface NavigationLinksSelect<T extends boolean = true> {
  label?: T;
  url?: T;
  external?: T;
  enabled?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidebar-groups_select".
 */
export interface SidebarGroupsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  enabled?: T;
  order?: T;
  defaultOpen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sidebar-items_select".
 */
export interface SidebarItemsSelect<T extends boolean = true> {
  label?: T;
  url?: T;
  description?: T;
  icon?: T;
  group?: T;
  parent?: T;
  external?: T;
  enabled?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components_select".
 */
export interface ComponentsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  description?: T;
  placeholder?: T;
  configuration?: T;
  preview?: T;
  enabled?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-api-specs_select".
 */
export interface OpenApiSpecsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  version?: T;
  specFile?: T;
  baseUrl?: T;
  slug?: T;
  servers?:
    | T
    | {
        url?: T;
        description?: T;
        id?: T;
      };
  authentication?:
    | T
    | {
        type?: T;
        apiKeyName?: T;
        apiKeyLocation?: T;
      };
  enabled?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}